#!/usr/bin/env python
import subprocess, time, json, pickle, os

user = os.getlogin()

def execute_and_capture(cmd):
  try:
    process = subprocess.run(cmd, capture_output=True, text=True, shell=True)
    output = process.stdout.strip()
    return output
  except subprocess.CalledProcessError:
    return ""

command_workspace = "hyprctl activeworkspace -j"
command_windows = "hyprctl clients -j"
windower = {}
tabber = {}
if(os.path.exists(f"/usr/local/bin/apps")):
      with open(f"/usr/local/bin/apps", "rb") as f:
        tabber = pickle.load(f)
if(os.path.exists(f"/usr/local/bin/all")):
      with open(f"/usr/local/bin/all", "rb") as f:
        windower = pickle.load(f)

while(True):
  time.sleep(1)
  output_string = execute_and_capture(command_workspace)

  workspace = json.loads(output_string)['id']
  output_string = execute_and_capture(command_windows)
  windows = json.loads(output_string)
  for i in windows:
    if i["workspace"]["id"] == workspace:
      print(i['title'] + "####" + i['class'])
      tab = i['title']
      title = i['class']
      if tab not in tabber:
        tabber[tab] = 1
      else:
        tabber[tab] += 1
      if title not in windower:
        windower[title] = 1
      else:
        windower[title] += 1
    else:
          news = execute_and_capture("hyprctl activewindow -j")
          news = json.loads(news)
          if news['workspace']['id'] < 0:
            tab = news['title']
            title = news['class']
            if tab not in tabber:
              tabber[tab] = 1
            else:
              tabber[tab] += 1
            if title not in windower:
              windower[title] = 1
            else:
              windower[title] += 1
    with open(f"/usr/local/bin/apps", "wb") as f:
      pickle.dump(tabber, f);
    with open(f"/usr/local/bin/all", "wb") as f:
      pickle.dump(windower, f);

