#!/usr/bin/env python
import subprocess, time, json, pickle, os

user = os.getlogin()

def execute_and_capture(cmd):
  try:
    process = subprocess.run(cmd, capture_output=True, text=True, shell=True)
    output = process.stdout.strip()
    return output
  except subprocess.CalledProcessError:
    return ""
cwd = os.getlogin()
command_workspace = "hyprctl activeworkspace -j"
command_windows = "hyprctl clients -j"
windower = {}
tabber = {}
if(os.path.exists(f"/home/{cwd}/apps")):
      with open(f"/usr/local/bin/apps", "rb") as f:
        tabber = pickle.load(f)
if(os.path.exists(f"/home/{cwd}/all")):
      with open(f"/home/{cwd}/all", "rb") as f:
        windower = pickle.load(f)
print("Started!")
while(True):
  try:
    time.sleep(1)
    output_string = execute_and_capture(command_workspace)

    workspace = json.loads(output_string)['id']
    output_string = execute_and_capture(command_windows)
    windows = json.loads(output_string)
    for i in windows:
      if i["workspace"]["id"] == workspace:
        tab = i['title']
        title = i['class']
        if tab not in tabber:
          tabber[tab] = 1
        else:
          tabber[tab] += 1
        if title not in windower:
          windower[title] = 1
        else:
          windower[title] += 1
      else:
            news = execute_and_capture("hyprctl activewindow -j")
            news = json.loads(news)
            if news['workspace']['id'] < 0:
              tab = news['title']
              title = news['class']
              if tab not in tabber:
                tabber[tab] = 1
              else:
                tabber[tab] += 1
              if title not in windower:
                windower[title] = 1
              else:
                windower[title] += 1
      with open(f"/home/{cwd}/apps", "wb") as f:
        pickle.dump(tabber, f);
      with open(f"/home/{cwd}/all", "wb") as f:
        pickle.dump(windower, f);
  except:
        continue

